### ISSUE TITLE
歌曲播放几首就不播放了，需要手动点击播放

### ISSUE THREAD

**Issue by Julianduu** [listen1/listen1_desktop#474]
平台：Windows 10 64位
Listen1版本：2.21.4 便携版
歌曲播放几首就不播放了，需要手动点击播放

**Comment by listen1** [comment]
能否在开发者工具的console窗口中看一下报错日志，谢谢

**Comment by ElementClock** [comment]
桌面版也是这样的。

**Comment by Julianduu** [comment]
> 能否在开发者工具的console窗口中看一下报错日志，谢谢

Failed to load resource: net::ERR_CONNECTION_RESET
angular.min.js:129 Error: Network Error
    at e.exports (axios.min.js:2)
    at XMLHttpRequest.l.onerror (axios.min.js:2) "Possibly unhandled rejection: {"message":"Network Error","name":"Error","stack":"Error: Network Error\n    at e.exports (file:///D:/Software/Listen1/resources/app.asar/listen1_chrome_extension/js/vendor/axios.min.js:2:9719)\n    at XMLHttpRequest.l.onerror (file:///D:/Software/Listen1/resources/app.asar/listen1_chrome_extension/js/vendor/axios.min.js:2:8491)","config":{"url":"https://api.github.com/repos/listen1/listen1_chrome_extension/releases/latest","method":"get","headers":{"Accept":"application/json, text/plain, */*"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1}}"
Uncaught (in promise) Error: Network Error
    at e.exports (axios.min.js:2)
    at XMLHttpRequest.l.onerror (axios.min.js:2)

**Comment by listen1** [comment]
看错误可能是网络原因，是否能换一个网络重新测试一下？谢谢
