### ISSUE TITLE
Listen1 绿色免安装版的建议

### ISSUE THREAD

**Issue by listen1** [listen1/listen1_desktop#70]
有人提议出一个免安装版本，除了免除了安装步骤，更重要的是把歌单等记录保存在目录下，这样可以把Listen1放进U盘，插到哪播到哪的体验。

**Comment by Zephyr006** [comment]
支持免安装版！
ps.我想自己打包安装包，但是始终报错，如果有时间麻烦指导一下，报错信息如下（希望免安装版能提供更便捷的打包方式）：

>  Listen1@2.1.2 dist:win64 /root/data/listen1_desktop-2.1.2
> electron-builder --win --x64

  • electron-builder version=20.38.5
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=3.1.1 appOutDir=dist/win-unpacked
  ⨯ error: exit status 193
path: /usr/bin/wine
args: wine /root/.cache/electron-builder/winCodeSign/winCodeSign-2.4.0/rcedit-ia32.exe /root/data/listen1_desktop-2.1.2/dist/win-unpacked/Listen1.exe --set-version-string FileDescription Listen1 --set-version-string ProductName Listen1 --set-version-string LegalCopyright Copyright © 2019 Listen 1 --set-file-version 2.1.2 --set-product-version 2.1.2.0 --set-version-string InternalName Listen1 --set-version-string OriginalFilename  --set-version-string CompanyName Listen 1 --set-icon /root/data/listen1_desktop-2.1.2/build/icon.ico
output: 
error output:000f:err:service:process_send_command receiving command result timed out
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"WineBus" failed to start: 1053
wine: Z:\root\.cache\electron-builder\winCodeSign\winCodeSign-2.4.0\rcedit-ia32.exe 的 EXE 格式无效。

github.com/develar/app-builder/pkg/util.Execute
	/Volumes/data/Documents/app-builder/pkg/util/util.go:75
github.com/develar/app-builder/pkg/wine.execWine
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:88
github.com/develar/app-builder/pkg/wine.ConfigureCommand.func2
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:43
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	/Volumes/data/Documents/app-builder/main.go:78
runtime.main
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/proc.go:201
runtime.goexit
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/asm_amd64.s:1333

Error: /root/data/listen1_desktop-2.1.2/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/root/data/listen1_desktop-2.1.2/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:217:13)
    at ChildProcess.emit (events.js:125:13)
    at maybeClose (internal/child_process.js:933:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
From previous event:
    at runCallback (timers.js:757:18)
    at tryOnImmediate (timers.js:718:5)
    at processImmediate [as _immediateCallback] (timers.js:698:5)
From previous event:
    at WinPackager.signAndEditResources (/root/data/listen1_desktop-2.1.2/node_modules/app-builder-lib/src/winPackager.ts:260:158)
    at _bluebirdLst.default.map.file (/root/data/listen1_desktop-2.1.2/node_modules/app-builder-lib/src/winPackager.ts:363:21)
    at go$readdir$cb (/root/data/listen1_desktop-2.1.2/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqWrap.oncomplete (fs.js:153:20)
From previous event:
    at /root/data/listen1_desktop-2.1.2/node_modules/app-builder-lib/src/winPackager.ts:361:27
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (/root/data/listen1_desktop-2.1.2/node_modules/app-builder-lib/src/winPackager.ts:355:73)
    at /root/data/listen1_desktop-2.1.2/node_modules/app-builder-lib/src/platformPackager.ts:250:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:757:18)
    at tryOnImmediate (timers.js:718:5)
    at processImmediate [as _immediateCallback] (timers.js:698:5)
From previous event:
    at WinPackager.doPack (/root/data/listen1_desktop-2.1.2/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /root/data/listen1_desktop-2.1.2/node_modules/app-builder-lib/src/platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/root/data/listen1_desktop-2.1.2/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /root/data/listen1_desktop-2.1.2/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/root/data/listen1_desktop-2.1.2/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /root/data/listen1_desktop-2.1.2/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:171:5)
From previous event:
    at Packager.doBuild (/root/data/listen1_desktop-2.1.2/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /root/data/listen1_desktop-2.1.2/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /root/data/listen1_desktop-2.1.2/node_modules/graceful-fs/graceful-fs.js:111:16
    at /root/data/listen1_desktop-2.1.2/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:153:20)
From previous event:
    at Packager._build (/root/data/listen1_desktop-2.1.2/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /root/data/listen1_desktop-2.1.2/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:757:18)
    at tryOnImmediate (timers.js:718:5)
    at processImmediate [as _immediateCallback] (timers.js:698:5)
From previous event:
    at Packager.build (/root/data/listen1_desktop-2.1.2/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/root/data/listen1_desktop-2.1.2/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/root/data/listen1_desktop-2.1.2/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/root/data/listen1_desktop-2.1.2/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Listen1@2.1.2 dist:win64: `electron-builder --win --x64`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Listen1@2.1.2 dist:win64 script.

**Comment by Zephyr006** [comment]
问题已解决，愿Listen1越来越好，期待免安装版！

**Comment by BingoKingo** [comment]
免安装版不是直接从exe里面的文件夹里直接提取app_64.7z吗？
